repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami
- name: fluent
  url: https://fluent.github.io/helm-charts
- name: nextcloud
  url: https://nextcloud.github.io/helm/

helmDefaults:
  wait: true
  createNamespace: true

releases:
  - name: ddns-updater
    namespace: tooling
    chart: ./ddns-updater
    version: 0.1.0
    values:
      - ./ddns-updater/values.lvb1.yaml

  - name: fluent-bit
    namespace: tooling
    chart: fluent/fluent-bit
    version: 0.19.17
    values:
      - ./fluent-bit/values.lvb1.yaml
    secrets:
      - ./fluent-bit/secrets.lvb1.yaml

  - name: upnp-cronjob
    namespace: tooling
    chart: ./upnp-cronjob
    values:
      - ./upnp-cronjob/lvb1.values.yaml

  # - name: nextcloud
  #   namespace: default
  #   chart: nextcloud/nextcloud
  #   version: 2.11.3
  #   values:
  #     - ./nextcloud/values.lvb1.yaml
