repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami
- name: fluent
  url: https://fluent.github.io/helm-charts
- name: nextcloud
  url: https://nextcloud.github.io/helm/

helmDefaults:
  wait: true
  createNamespace: true
  timeout: 600

releases:
  - name: ddns-updater
    namespace: tooling
    chart: ./ddns-updater
    version: 0.1.0
    values:
      - ./ddns-updater/values.lvb2.yaml

  - name: fluent-bit
    namespace: tooling
    chart: fluent/fluent-bit
    version: 0.19.17
    values:
      - ./fluent-bit/values.lvb2.yaml
    secrets:
      - ./fluent-bit/secrets.lvb2.yaml

  - name: upnp-cronjob
    namespace: tooling
    chart: ./upnp-cronjob
    values:
      - ./upnp-cronjob/values.lvb2.yaml
