repositories: []

helmDefaults:
  wait: true
  createNamespace: true
  timeout: 600

releases:

# Tailscale

- name: tailscale-relay
  namespace: default
  chart: tailscale-relay
  values:
  - tailscale-relay/values.lvb1.yaml
  secrets:
  - tailscale-relay/secrets.lvb1.yaml

# Ingresses

- name: ingress
  chart: ingress
  values: []
  secrets:
  - ingress/secrets.lvb1.yaml

# Kube-related

# - name: metrics-server
#   chart: metrics-server
#   values:
#   - ./metrics-server/values.lvb1.yaml

- name: priority-classes
  namespace: tooling
  chart: priority-classes
  values:
  - ./priority-classes/values.lvb1.yaml

# Services

- name: homer
  namespace: public
  chart: homer
  values:
  - homer/values.lvb1.yaml

- name: home-assistant
  namespace: local
  chart: home-assistant
  values:
  - home-assistant/values.lvb1.yaml

- name: deluge
  namespace: local
  chart: deluge
  values:
  - deluge/values.lvb1.yaml

# - name: minio
#   namespace: tooling
#   chart: minio
#   values:
#   - minio/values.lvb1.yaml
#   secrets:
#   - minio/secrets.lvb1.yaml
