repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami
- name: fluent
  url: https://fluent.github.io/helm-charts
- name: nextcloud
  url: https://nextcloud.github.io/helm/
- name: minio
  url: https://helm.min.io/

helmDefaults:
  wait: true
  createNamespace: true
  timeout: 600

releases:
  # # Tooling
  # - name: ddns-updater
  #   namespace: tooling
  #   chart: ./ddns-updater
  #   version: 0.1.0
  #   values:
  #     - ./ddns-updater/values.lvb1.yaml

  # - name: fluent-bit
  #   namespace: tooling
  #   chart: fluent/fluent-bit
  #   version: 0.19.17
  #   values:
  #     - ./fluent-bit/values.lvb1.yaml
  #   secrets:
  #     - ./fluent-bit/secrets.lvb1.yaml

  # - name: upnp-cronjob
  #   namespace: tooling
  #   chart: ./upnp-cronjob
  #   values:
  #     - ./upnp-cronjob/values.lvb1.yaml

  # # Services
  # - name: nextcloud
  #   namespace: default
  #   chart: nextcloud/nextcloud
  #   version: 2.11.3
  #   values:
  #     - ./nextcloud/values.lvb1.yaml

  - name: minio
    namespace: default
    chart: minio/minio
    version: 8.0.10
    values:
      - ./minio/values.lvb1.yaml
    # secrets:
      - ./minio/secrets.lvb1.yaml

  # - name: kafka
  #   namespace: default
  #   chart: bitnami/kafka
  #   # version: 3.4.8
  #   values:
  #     - ./kafka/values.lvb1.yaml
