apiVersion: v1
kind: Secret
metadata:
  name: admin.service-account-token
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: admin
type: kubernetes.io/service-account-token
