schedule: "0 * * * *"

image:
  repository: florianpiesche/miniupnpc
  tag: latest

podLabels:
  release: upnp-cronjob
  env: lvb2

serviceAccount:
  create: true
  name: upnp-cronjob

upnp:
  descriptionXmlUrl: http://192.168.1.1:49152/4c43774e/gatedesc0b.xml
  forwardPortsTcp: [ "6443", "41208:41208" ] # 80, 443 not allowed with upnp
  forwardPortsUdp: []
  forwardIp: "192.168.1.13" # Control-plane ip

resources: {}
