apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ddns-updater
  name: ddns-updater
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ddns-updater
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ddns-updater
        {{- if .Values.podLabels }}
{{ toYaml .Values.podLabels | indent 8 }}
        {{- end }}
    spec:
      containers:
      - image: qmcgaw/ddns-updater
        name: ddns-updater
        volumeMounts:
        - mountPath: /updater/data/
          name: config-volume
        env:
        - name: LOG_LEVEL
          value: {{ .Values.logLevel }}
      volumes:
      - name: config-volume
        hostPath:
          path: /mnt/ddns-updater-data
